FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y postgresql-client && apt-get clean

COPY wait-for-postgres.sh .

COPY . .

RUN chmod +x wait-for-postgres.sh

CMD ["sh", "-c", "./wait-for-postgres.sh postgres 5432 && alembic upgrade head && python seed.py && uvicorn main:app --host 0.0.0.0 --port 8000"]